---
- name: Update
  apt:
    update_cache: true
    name: redis-server
    state: latest
  notify:
  - restart redis.service
- name: Restart Redis Server
  service: name=redis state=restarted enabled=yes
...
