---
- name: Install Docker | Install playbook
  hosts: vpn
  tasks:
    - name: Amazon repository
      when: ansible_distribution == 'Amazon'
      block:
        - name: Amazon prepare | Search amazon-linux-extras packages
          ansible.builtin.shell: set -o pipefail && amazon-linux-extras list | awk '/enable/ {print$2,$3'}
          args:
            executable: /usr/bin/bash
          register: list_enable
          changed_when: false
        - name: Amazon prepare | Enable amazon-linux-extras packages
          ansible.builtin.command: amazon-linux-extras enable docker
          when: '"docker=latest enabled" not in list_enable.stdout'

    - name: Centos repository
      when: ansible_distribution == 'CentOS'
      block:
        - name: Centos repository | Uninstall all conflicting packages
          when: ansible_distribution == 'CentOS'
          yum:
            name: [docker, docker-client, docker-client-latest, docker-common, docker-latest, docker-latest-logrotate, docker-logrotate, docker-engine]
            state: absent
        - name: Centos repository | Installing yum-utils
          yum:
            name: yum-utils
            state: latest
        - name: Centos repository | Configuring docker-ce repo
          get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
            mode: "0644"

    - name: Apt repository
      when: ansible_distribution == 'Ubuntu' or  ansible_distribution == 'Debian'
      block:
        - name: Apt repository | Uninstall all conflicting packages
          apt:
            name: docker.io, docker-doc, docker-compose, docker-compose-v2, podman-docker, containerd, runc
            state: absent
        - name: Apt repository | Apt-key fetcheing
          apt_key:
            url: https://download.docker.com/linux/{{ ansible_distribution | lower}}/gpg
            keyring: /etc/apt/keyrings/docker.gpg
        - name: Ubuntu repository configured
          when: ansible_distribution == 'Ubuntu'
          apt_repository:
            repo: >-
              deb
              [arch=amd64
              signed-by=/etc/apt/keyrings/docker.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            filename: docker
        - name: Show debug info
          debug:
            msg: |
              deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable

        - name: Debian repository configured
          when: ansible_distribution == 'Debian'
          apt_repository:
            repo: >-
              deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
            filename: docker


    - name: Install Docker
      notify: Handlers | Enabled dockerd
      block:
        - name: Amazon Linux | Installing packages
          when: ansible_distribution == 'Amazon'
          yum:
            name: docker
            state: latest
            update_cache: true

        - name: Centos | Installing packages
          when: ansible_distribution == 'CentOS'
          yum:
            name: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]
            state: latest

        - name: Ubuntu | Installing packages
          when: ansible_distribution == 'Ubuntu' or  ansible_distribution == 'Debian'
          apt:
            name: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]
            update_cache: true
            state: latest

        - name: Show docker version
          ansible.builtin.shell: docker --version
          args:
            executable: /usr/bin/bash
          register: docker_version
          changed_when: false
        - name: Install Docker | Show docker version
          debug:
            msg: "{{ docker_version.stdout }}"

        # - name: Install Docker-compose | Get lastest docker-compose version
        #   uri:
        #     url: https://api.github.com/repos/docker/compose/releases/latest
        #     body_format: json
        #   register: version
        # - name: Install Docker-compose | Installing Docker-compose
        #   get_url:
        #     url: "https://github.com/docker/compose/releases/download/{{ version.json.tag_name }}/docker-compose-Linux-x86_64"
        #     dest: /usr/bin/docker-compose
        #     mode: "0755"

        # - name: Install Docker-compose | Show docker-compose version
        #   ansible.builtin.shell: docker-compose --version
        #   args:
        #     executable: /usr/bin/bash
        #   register: dc_ver
        #   changed_when: false
        # - name: Install Docker-compose | Show docker-compose version
        #   debug:
        #     msg: "{{ dc_ver.stdout }}"

  handlers:
    - name: Handlers | Enabled dockerd
      systemd:
        enabled: true
        name: docker
        masked: false
        daemon_reload: true
        state: restarted
...
