---
- name: Check ssh port numbers are accessible from the current host
  hosts: all
  gather_facts: no
  ignore_errors: true
  tasks:
    - name: check network ssh
      wait_for:
        host: "{{ ip }}"
        port: "{{ item }}"
        state: started
        delay: 0
        timeout: 3
      ignore_errors: true
      register: ssh_result
      with_items:
        - 22
      delegate_to: localhost
    - group_by: key=reachable
      when: ssh_result.failed is undefined
      delegate_to: localhost
    # - group_by: key=unreachable
    #   when: ssh_result.failed is defined
    - name: add network_unreachable file
      lineinfile:
        path: /tmp/network_unreachable
        line: 'CAN NOT CONNECT VIA NETWORK:'
        create: true
      delegate_to: localhost
    - name: add network_unreachable file
      lineinfile:
        path: /tmp/network_unreachable
        line: "{{ inventory_hostname  }}"      
        create: true
      when: ssh_result.failed is defined
      ignore_errors: true
      delegate_to: localhost
    - name: add network_unreachable Hostname to file
      lineinfile:
        path: /tmp/network_unreachable
        line: "{{ inventory_hostname  }}"      
        create: true
      when: ssh_result.failed is defined
      ignore_errors: true
      delegate_to: localhost

- name: Gather SSH reachable hosts
  hosts: reachable
  ignore_errors: true
  gather_facts: true
  tasks:
    - block:
        - set_fact:
            ssh_reachable: "{{ ansible_play_hosts }}"
        - set_fact:
            ssh_unreachable: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
        - name: add ssh_reachable file
          lineinfile:
            path: /tmp/ssh_reachable
            line: 'CAN SSH CONNECT HOSTS:'
            create: true
          delegate_to: localhost
        - name: add ssh_reachable file
          lineinfile:
            path: /tmp/ssh_reachable
            line: "{{ item }}"      
            create: true
          with_items: "{{ ssh_reachable }}"
          delegate_to: localhost
        - name: add ssh_unreachable file
          lineinfile:
            path: /tmp/ssh_unreachable
            line: 'FAILED SSH CONNECT HOSTS:'
            create: true
          delegate_to: localhost
        - name: add ssh_unreachable file
          lineinfile:
            path: /tmp/ssh_unreachable
            line: "{{ item }}"      
            create: true
          with_items: "{{ ssh_unreachable }}"
          delegate_to: localhost
      run_once: true
