---
- name: Install python | Install playbook
  hosts: "{{ lookup('env', 'HOST') }}"
  tasks:
      - name: Prepare host | Check for Python
        raw: test -e /usr/bin/python
        changed_when: false
        failed_when: false
        register: check_python

      - name: Prepare host | Install Python
        raw: test -e /usr/bin/apt && (apt -y update && apt install -y python3) || (yum -y install python3 python)
        when: check_python.rc != 0

    # - name: Prepare host | Check that the /usr/bin/python exists
    #   stat:
    #     path: /usr/bin/python
    #   register: stat_result

    # - name: Prepare host | Find python path
    #   when: not stat_result.stat.exists
    #   block:
    #     - name: Prepare host | Find python path
    #       shell: which python3
    #       args:
    #         executable: /usr/bin/bash
    #       register: python3_path
    #       changed_when: false

    #     - name: Prepare host | Install Python
    #       raw: test -e /usr/bin/apt && (apt -y update && apt install -y python3) || (yum -y install python3 python)
    #       when: not python3_path.stdout

    #     - name: Prepare host | Print python3 path
    #       debug:
    #         msg: "{{ python3_path.stdout }}"

    #     - name: Prepare host | Create a symbolic link
    #       file:
    #         src: "{{ python3_path.stdout }}"
    #         dest: /usr/bin/python
    #         owner: root
    #         group: root
    #         state: link
