---
- name: Syncing prom cfg
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: prometheus.yml.j2, dest: /etc/prometheus/prometheus.yml, owner: root, group: root, mode: 644 }

- name: Reloading prometheus daemon
  service:
    name: prometheus
    state: reloaded
    enabled: yes
