---
- name: restart etcd
  command: /bin/true
  notify:
    - Backup etcd data
    - reload etcd
    - wait for etcd up

- import_tasks: backup.yml

- name: reload etcd
  systemd:
    name: etcd
    daemon_reload: true
    state: restarted

- name: wait for etcd up
  uri:
    url: "https://127.0.0.1:2379/health"
    validate_certs: false
    client_cert: "{{ etcd_node_crt }}"
    client_key: "{{ etcd_node_key }}"
  register: __result
  until: __result.status is defined and __result.status == 200
  retries: 60
  delay: 1
...
