---
- name: Edit deploy and sts
  shell: |
    kubectl -n "{{ k8s_ns }}" get deploy,sts --no-headers=true | awk '{print $1 }'| xargs -I line kubectl -n "{{ k8s_ns }}" patch line --type json -p='[{"op":"replace","path":"/spec/replicas", "value":1}]'

- name: Edit CronJobs
  shell: |
    kubectl -n "{{ k8s_ns }}" get cj --no-headers=true | awk '{print $1}'| xargs -I line kubectl -n "{{ k8s_ns }}" patch cj line --type json -p='[{"op":"replace","path":"/spec/suspend", "value":false}]'

- name: Edit Label run
  shell: |
    kubectl label ns "{{ k8s_ns }}" run=1 --overwrite

- name: Edit Label free
  shell: |
    kubectl label ns "{{ k8s_ns }}" free=1 --overwrite

- name: Get UnixTime
  shell: date +%s
  register: standTime

- name: Print standTime
  debug:
    var: standTime.stdout

- name: Change standDieTime
  set_fact:
    standDieTime: "{{ standTime.stdout|int * 1000|int + 25200000|int }}"

- name: Print standDieTime
  debug:
    var: standDieTime

- name: Edit Label started_at
  shell: |
    kubectl label ns "{{ k8s_ns }}" started_at="{{ standDieTime }}" --overwrite
...
