- name: Installing grafana-dashboard
  delegate_to: grafana
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: sql-exporter-dashboard.json.j2, dest: /var/lib/grafana/dashboards/custom-dashboards/sql-exporter-dashboard.json, owner: grafana, group: grafana, mode: 644 }
  tags: grafana
