---
- name: Not AWS Linux | CentOS 7.9 info
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_version == '7.9'
  debug:
    msg: "{{ ansible_distribution }} version {{ ansible_distribution_version }} has real IP {{ ansible_default_ipv4.address }} based on {{ ansible_virtualization_type }}"

- name: Not AWS Linux | CentOS info
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_version != '7.9'
  debug:
    msg: "{{ ansible_distribution }} version {{ ansible_distribution_version }} has real IP {{ ansible_default_ipv4.address }} based on {{ ansible_virtualization_type }}"

- name: Not AWS Linux | Ubuntu info
  when:
    - ansible_distribution == 'Ubuntu'
  debug:
    msg: "{{ ansible_distribution }} version {{ ansible_distribution_version }} has real IP {{ ansible_default_ipv4.address }} based on {{ ansible_virtualization_type }}"

- name: Not AWS Linux | Other linux info
  when:
    - ansible_distribution != 'CentOS'
    - ansible_distribution != 'Ubuntu'
  debug:
    msg: "{{ ansible_distribution }} version {{ ansible_distribution_version }} has real IP {{ ansible_default_ipv4.address }} based on {{ ansible_virtualization_type }}"
