groups:
  - name: blackbox-exporter
    rules:
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 1m
        labels:
          severity: error
        annotations:
          summary: 'Blackbox probe failed for {{ $labels.target }})'
          description: 'Probe failed, `VALUE = {{ $value }}`  INSTANCE: {{ $labels }}'
      - alert: BlackboxBadHTTP
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'Blackbox probe HTTP failure for {{ $labels.instance }}'
          description: 'HTTP status code is not 200-399  VALUE = {{ $value }} INSTANCE = {{ $labels }}'
