---
- name: Adding telegraf-agent repo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: influxdb.repo, dest: /etc/yum.repos.d, owner: root, group: root, mode: 644 }

- name: Telegraf-agent | Install telegraf-agent
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - telegraf

- name: Telegraf-agent | Starting telegraf-agent
  service:
    name: telegraf
    state: started
    enabled: yes
