---
  - include: centos.yml
    when: ansible_distribution == "CentOS"

  - include: debian.yml
    when: ansible_distribution == "Debian"

  - include: ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - include: configure.yml

  - include: run.yml
