---

  - include: centos-7.yml
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - include: centos-8.yml
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

  - include: ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - include: debian.yml
    when: ansible_distribution == "Debian"
