---
- name: Install gpg && apt-transport-https && software-properties-common && dirmngr
  apt:
    name:
    - gpg
    - apt-transport-https
    - software-properties-common
    - dirmngr
- name: Add apt-key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
- name: Install pub keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 'D27D666CD88E42B4'
- name: Add repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
    filename: elk
    update_cache: false
- name: Install beats
  apt:
    name:
    - metricbeat
    - filebeat
    update_cache: true
    state: latest
- name: Place a config metricbeat
  copy:
    src: templates/beats/metricbeat.yml
    dest: /etc/metricbeat/metricbeat.yml
    mode: '0644'
    owner: root
    group: root
  become: true
- name: Place a config filebeat
  copy:
    src: templates/beats/host.filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    mode: '0600'
    owner: root
    group: root
  become: true
- name: Systemd check
  systemd:
    enabled: true
    name: "{{ item }}"
    masked: false
    state: restarted
  with_items: ['filebeat', 'metricbeat']
...
