---
- name: Join Member | Add member to etcd cluster  # noqa 301 305
  shell: "{{ etcd_bin_dir }}/etcdctl member add {{ etcd_member_name }} --peer-urls={{ etcd_peer_url }}"
  register: etcd_member_add_result
  until: etcd_member_add_result.rc == 0 or 'Peer URLs already exists' in member_add_result.stderr
  failed_when: etcd_member_add_result.rc != 0 and 'Peer URLs already exists' not in etcd_member_add_result.stderr
  retries: "{{ etcd_retries }}"
  delay: "{{ retcd_etry_stagger | random + 3 }}"
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_node_crt }}"
    ETCDCTL_KEY: "{{ etcd_node_key }}"
    ETCDCTL_CACERT: "{{ etcd_ca_crt }}"
    ETCDCTL_ENDPOINTS: "{{ etcd_addresses }}"

- include_tasks: refresh_config.yml
  vars:
    etcd_peer_addresses: >-
      {% for host in groups[etcd_inventory_group] -%}
        {%- if hostvars[host]['etcd_member_in_cluster'].rc == 0 -%}
          {{ "etcd"+loop.index|string }}=https://{{ hostvars[host].etcd_address }}:2380,
        {%- endif -%}
        {%- if loop.last -%}
          {{ etcd_member_name }}={{ etcd_peer_url }}
        {%- endif -%}
      {%- endfor -%}

- name: Join Member | Ensure member is in etcd cluster
  shell: "set -o pipefail && {{ etcd_bin_dir }}/etcdctl member list | grep {{ etcd_address }} >/dev/null"
  args:
    executable: /bin/bash
  register: etcd_member_in_cluster
  changed_when: false
  check_mode: false
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}.pem"
    ETCDCTL_KEY: "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}-key.pem"
    ETCDCTL_CACERT: "{{ etcd_cert_dir }}/ca.pem"
    ETCDCTL_ENDPOINTS: "{{ etcd_access_addresses }}"

- name: Configure | Ensure etcd is running
  systemd:
    name: etcd
    state: started
    enabled: true
    daemon_reload: true
...
