---
- name: Start Elasticsearch
  systemd:
    name: elasticsearch
    state: started

- name: Enable Elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
