---
- name: set fact
  import_tasks: set_fact.yml

- name: add hashicorp repo
  get_url:
    url: "{{ vault_repo }}"
    dest: /etc/yum.repos.d/

- name: install vault
  package:
    name:
      - vault

- name: create config
  template:
    src: vault.hcl.j2
    dest: "{{ vault_conf_dir }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    backup: true
  notify: vault need restart

- name: start etcd
  systemd:
    name: vault
    state: started
    enabled: true
    daemon_reload: true
...
